name: Testing Java

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Mempersiapkan JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Testing menggunakan maven
        run: mvn --batch-mode --update-snapshots verify