name: Testing Java

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Mempersiapkan JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Buat menggunakan maven
        run: mvn --batch-mode --update-snapshots package assembly:single
      - name: Buat Release di github
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            bin/tubes-algeo.jar
